import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Open_Sans, Itim } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

const itim = Itim({
  variable: "--font-itim",
  subsets: ["latin"],
  weight: "400"
});
const inter = Itim({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Longevity",
  description: "Generated by create next app",
};





// TODO: Add clerk setup
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
         className={`${geistSans.variable} ${geistMono.variable} ${openSans.variable} ${itim.variable} ${inter.variable} antialiased`}

      >

        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
